[project]
name = "analytics"
version = "0.4"
dependencies = [
    "python-dotenv",
    "statsmodels",
    "numpy",
    "pydantic",
    "asyncio",
    "fastapi",
    "uvicorn"
]

[project.optional-dependencies]
dev = ["black", "flake8"]
