version: '4.1'

services:
  neo4j_etl:
    build:
      context: ./neo4j_etl
    env_file:
      - .env
  
  analytics:
    build:
      context: ./analytics
    env_file:
      - .env
    ports:
      - "8032:8032"
    networks:
      - chatbot-network
    depends_on:
      - neo4j_etl

  chat_api:
    build:
      context: ./chat_api
    depends_on:
      - analytics
    env_file:
      - .env
    ports:
      - "8031:8031"
    networks:
      - chatbot-network

  chat_bot:
    build:
      context: ./chat_bot
    depends_on:
      - chat_api
    env_file:
      - .env
    ports:
      - "8501:8501"
    networks:
      - chatbot-network


networks:
  chatbot-network:
    driver: bridge
