version: '3.9'

services:
  analytics:
    build:
      context: ./analytics
    ports:
      - "8032:8032"
    networks:
      - chatbot-network

  chat_api:
    build:
      context: ./chat_api

    depends_on:
      - analytics  
    ports:
      - "8031:8031"
    networks:
      - chatbot-network

  chat_bot:
    build:
      context: ./chat_bot
    depends_on:
      - chat_api
    ports:
      - "8501:8501"
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
